### ISSUE TITLE
Linux Drivers for CC2540

### ISSUE THREAD

**Issue by kyleterry** [Harper04/Python-for-TI-CC2540#2]
I can't seem to get this to work on Arch or Ubuntu. Did you have to patch the device ID into the kernel or are you using an already patched kernel that can see this dongle?

**Comment by guimillet** [comment]
I did nothing with the kernel. I started to use the USB dongle with Ubuntu 12.10. It communicates through serial communication on port /dev/ttyACM0.

**Comment by Harper04** [comment]
This Code assumes that you gotyour dongle installed and working as a serial device. Kernel drivers are out of scope;)
